// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.21.0";

// src/lib/mcp/tools/list-tables.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.21.0";
var TABLES = [
  "menu_items",
  "categories",
  "tables",
  "pos_orders",
  "transactions",
  "raw_materials",
  "recipes",
  "supplies",
  "inv_products",
  "inv_daily_entries",
  "inv_next_day_stock",
  "shift_turns",
  "staff_members",
  "user_roles",
  "supplier_orders",
  "product_costs",
  "fiscal_receipts",
  "audit_log",
  "app_logs",
  "feedback",
  "print_jobs",
  "orders",
  "order_items_split",
  "service_requests",
  "song_requests",
  "chat_sessions",
  "ai_knowledge",
  "app_settings"
];
var list_tables_default = defineTool({
  name: "list_tables",
  title: "List database tables",
  description: "List all public tables available in the Boulevard Caf\xE9 database.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(TABLES, null, 2) }],
    structuredContent: { tables: TABLES }
  })
});

// src/lib/mcp/tools/select-rows.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.21.0";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser(ctx) {
  const env = globalThis.process?.env ?? {};
  return createClient(
    env.SUPABASE_URL,
    env.SUPABASE_PUBLISHABLE_KEY ?? env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var select_rows_default = defineTool2({
  name: "select_rows",
  title: "Read rows from a table",
  description: "Read rows from a Boulevard Caf\xE9 public table. Respects RLS as the signed-in user. Use `list_tables` first to see valid names.",
  inputSchema: {
    table: z.enum(TABLES).describe("Table name"),
    columns: z.string().optional().describe("Comma-separated columns, or '*' for all. Default '*'."),
    limit: z.number().int().min(1).max(200).optional().describe("Row limit (max 200). Default 50."),
    orderBy: z.string().optional().describe("Column to order by."),
    ascending: z.boolean().optional().describe("Ascending order. Default false (newest first when using created_at).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ table, columns, limit, orderBy, ascending }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    let q = sb.from(table).select(columns || "*").limit(limit ?? 50);
    if (orderBy) q = q.order(orderBy, { ascending: ascending ?? false });
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { rows: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "taqrxxikhwghmeofrpzs";
var mcp_default = defineMcp({
  name: "boulevard-cafe-mcp",
  title: "Boulevard Caf\xE9 MCP",
  version: "0.1.0",
  instructions: "Read-only access to the Boulevard Caf\xE9 database (Lovable Cloud). Use `list_tables` to see what's available, then `select_rows` to fetch data. All access is scoped to the signed-in manager's RLS permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_tables_default, select_rows_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.21.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
